CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'zone_treasurer')),
  zone_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.zones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  treasurer_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_id BIGINT NOT NULL REFERENCES public.zones(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  address TEXT,
  phone TEXT,
  start_year INTEGER NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.monthly_due_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year INTEGER NOT NULL UNIQUE,
  monthly_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
  yearly_due NUMERIC(10,2) NOT NULL DEFAULT 0,
  active_threshold NUMERIC(10,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.monthly_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  year INTEGER NOT NULL,
  month TEXT NOT NULL CHECK (month IN ('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec')),
  amount NUMERIC(10,2) NOT NULL DEFAULT 0,
  paid BOOLEAN NOT NULL DEFAULT FALSE,
  paid_date TIMESTAMPTZ,
  recorded_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (member_id, year, month)
);

CREATE TABLE IF NOT EXISTS public.additional_fees (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  amount NUMERIC(10,2) NOT NULL DEFAULT 0,
  year INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.additional_fee_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fee_id TEXT NOT NULL REFERENCES public.additional_fees(id) ON DELETE CASCADE,
  member_id BIGINT NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  year INTEGER NOT NULL,
  amount NUMERIC(10,2) NOT NULL DEFAULT 0,
  paid BOOLEAN NOT NULL DEFAULT FALSE,
  paid_date TIMESTAMPTZ,
  recorded_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (fee_id, member_id, year)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'profiles_zone_fk'
      AND conrelid = 'public.profiles'::regclass
  ) THEN
    ALTER TABLE public.profiles
      ADD CONSTRAINT profiles_zone_fk
      FOREIGN KEY (zone_id) REFERENCES public.zones(id)
      ON DELETE SET NULL;
  END IF;
END $$;

ALTER TABLE public.members
  ADD COLUMN IF NOT EXISTS start_year INTEGER;

UPDATE public.members
SET start_year = EXTRACT(YEAR FROM created_at)::INTEGER
WHERE start_year IS NULL;

ALTER TABLE public.members
  ALTER COLUMN start_year SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_members_start_year ON public.members(start_year);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'zones_treasurer_fk'
      AND conrelid = 'public.zones'::regclass
  ) THEN
    ALTER TABLE public.zones
      ADD CONSTRAINT zones_treasurer_fk
      FOREIGN KEY (treasurer_id) REFERENCES public.profiles(id)
      ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);
CREATE INDEX IF NOT EXISTS idx_profiles_zone_id ON public.profiles(zone_id);
CREATE INDEX IF NOT EXISTS idx_members_zone_id ON public.members(zone_id);
CREATE INDEX IF NOT EXISTS idx_monthly_payments_member_year ON public.monthly_payments(member_id, year);
CREATE INDEX IF NOT EXISTS idx_additional_fee_payments_member_fee ON public.additional_fee_payments(member_id, fee_id);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_due_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.additional_fees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.additional_fee_payments ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, name, email, role, zone_id)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'username', NULL),
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.email),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'role', 'zone_treasurer'),
    NULLIF(NEW.raw_user_meta_data->>'zone_id', '')::BIGINT
  )
  ON CONFLICT (id) DO UPDATE
  SET username = EXCLUDED.username,
      name = EXCLUDED.name,
      email = EXCLUDED.email,
      role = EXCLUDED.role,
      zone_id = EXCLUDED.zone_id;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT OR UPDATE OF email, raw_user_meta_data ON auth.users
FOR EACH ROW
EXECUTE PROCEDURE public.handle_new_user();

DROP POLICY IF EXISTS "profiles_select_own" ON public.profiles;
DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;
DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
DROP POLICY IF EXISTS "profiles_delete_admin" ON public.profiles;
DROP POLICY IF EXISTS "zones_read_access" ON public.zones;
DROP POLICY IF EXISTS "members_select_access" ON public.members;
DROP POLICY IF EXISTS "members_insert_access" ON public.members;
DROP POLICY IF EXISTS "members_update_access" ON public.members;
DROP POLICY IF EXISTS "members_delete_access" ON public.members;
DROP POLICY IF EXISTS "monthly_due_settings_read" ON public.monthly_due_settings;
DROP POLICY IF EXISTS "monthly_due_settings_insert_admin" ON public.monthly_due_settings;
DROP POLICY IF EXISTS "monthly_due_settings_update_admin" ON public.monthly_due_settings;
DROP POLICY IF EXISTS "monthly_due_settings_delete_admin" ON public.monthly_due_settings;
DROP POLICY IF EXISTS "monthly_payments_select_access" ON public.monthly_payments;
DROP POLICY IF EXISTS "monthly_payments_insert_access" ON public.monthly_payments;
DROP POLICY IF EXISTS "monthly_payments_update_access" ON public.monthly_payments;
DROP POLICY IF EXISTS "monthly_payments_delete_access" ON public.monthly_payments;
DROP POLICY IF EXISTS "additional_fees_read" ON public.additional_fees;
DROP POLICY IF EXISTS "additional_fees_insert_admin" ON public.additional_fees;
DROP POLICY IF EXISTS "additional_fees_update_admin" ON public.additional_fees;
DROP POLICY IF EXISTS "additional_fees_delete_admin" ON public.additional_fees;
DROP POLICY IF EXISTS "additional_fee_payments_select_access" ON public.additional_fee_payments;
DROP POLICY IF EXISTS "additional_fee_payments_insert_access" ON public.additional_fee_payments;
DROP POLICY IF EXISTS "additional_fee_payments_update_access" ON public.additional_fee_payments;
DROP POLICY IF EXISTS "additional_fee_payments_delete_access" ON public.additional_fee_payments;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid()
      AND role = 'admin'
  )
  OR COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin';
$$;

CREATE POLICY "profiles_select_own"
  ON public.profiles
  FOR SELECT
  USING (
    id = auth.uid()
    OR public.is_admin()
  );
CREATE POLICY "profiles_insert_own"
  ON public.profiles
  FOR INSERT
  WITH CHECK (id = auth.uid());

CREATE POLICY "profiles_update_own"
  ON public.profiles
  FOR UPDATE
  USING (
    id = auth.uid()
    OR public.is_admin()
  )
  WITH CHECK (
    id = auth.uid()
    OR public.is_admin()
  );

CREATE POLICY "profiles_delete_admin"
  ON public.profiles
  FOR DELETE
  USING (public.is_admin() AND role = 'zone_treasurer');

CREATE POLICY "zones_read_access"
  ON public.zones
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
    OR treasurer_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.zone_id = public.zones.id
    )
  );

CREATE POLICY "members_select_access"
  ON public.members
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.zone_id = public.members.zone_id
    )
  );

CREATE POLICY "members_insert_access"
  ON public.members
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.zone_id = public.members.zone_id
    )
  );

CREATE POLICY "members_update_access"
  ON public.members
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.zone_id = public.members.zone_id
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.zone_id = public.members.zone_id
    )
  );

CREATE POLICY "members_delete_access"
  ON public.members
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.zone_id = public.members.zone_id
    )
  );

CREATE POLICY "monthly_due_settings_read"
  ON public.monthly_due_settings
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "monthly_due_settings_insert_admin"
  ON public.monthly_due_settings
  FOR INSERT
  WITH CHECK (public.is_admin());

CREATE POLICY "monthly_due_settings_update_admin"
  ON public.monthly_due_settings
  FOR UPDATE
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE POLICY "monthly_due_settings_delete_admin"
  ON public.monthly_due_settings
  FOR DELETE
  USING (public.is_admin());

CREATE POLICY "monthly_payments_select_access"
  ON public.monthly_payments
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.members m
      JOIN public.profiles p ON p.zone_id = m.zone_id
      WHERE m.id = public.monthly_payments.member_id
        AND p.id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

CREATE POLICY "monthly_payments_insert_access"
  ON public.monthly_payments
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.members m
      JOIN public.profiles p ON p.zone_id = m.zone_id
      WHERE m.id = public.monthly_payments.member_id
        AND p.id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

CREATE POLICY "monthly_payments_update_access"
  ON public.monthly_payments
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM public.members m
      JOIN public.profiles p ON p.zone_id = m.zone_id
      WHERE m.id = public.monthly_payments.member_id
        AND p.id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.members m
      JOIN public.profiles p ON p.zone_id = m.zone_id
      WHERE m.id = public.monthly_payments.member_id
        AND p.id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

CREATE POLICY "monthly_payments_delete_access"
  ON public.monthly_payments
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1
      FROM public.members m
      JOIN public.profiles p ON p.zone_id = m.zone_id
      WHERE m.id = public.monthly_payments.member_id
        AND p.id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

CREATE POLICY "additional_fees_read"
  ON public.additional_fees
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "additional_fees_insert_admin"
  ON public.additional_fees
  FOR INSERT
  WITH CHECK (public.is_admin());

CREATE POLICY "additional_fees_update_admin"
  ON public.additional_fees
  FOR UPDATE
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE POLICY "additional_fees_delete_admin"
  ON public.additional_fees
  FOR DELETE
  USING (public.is_admin());

CREATE POLICY "additional_fee_payments_select_access"
  ON public.additional_fee_payments
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.members m
      JOIN public.profiles p ON p.zone_id = m.zone_id
      WHERE m.id = public.additional_fee_payments.member_id
        AND p.id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

CREATE POLICY "additional_fee_payments_insert_access"
  ON public.additional_fee_payments
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.members m
      JOIN public.profiles p ON p.zone_id = m.zone_id
      WHERE m.id = public.additional_fee_payments.member_id
        AND p.id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

CREATE POLICY "additional_fee_payments_update_access"
  ON public.additional_fee_payments
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM public.members m
      JOIN public.profiles p ON p.zone_id = m.zone_id
      WHERE m.id = public.additional_fee_payments.member_id
        AND p.id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.members m
      JOIN public.profiles p ON p.zone_id = m.zone_id
      WHERE m.id = public.additional_fee_payments.member_id
        AND p.id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

CREATE POLICY "additional_fee_payments_delete_access"
  ON public.additional_fee_payments
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1
      FROM public.members m
      JOIN public.profiles p ON p.zone_id = m.zone_id
      WHERE m.id = public.additional_fee_payments.member_id
        AND p.id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

