CREATE TABLE IF NOT EXISTS public.sms_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT REFERENCES public.members(id) ON DELETE SET NULL,
  phone TEXT NOT NULL DEFAULT '',
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('sent', 'failed', 'no_phone', 'pending')),
  provider TEXT DEFAULT 'semaphore',
  provider_response JSONB,
  payment_key TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sms_logs_member_created_at
  ON public.sms_logs(member_id, created_at DESC);

ALTER TABLE public.sms_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "sms_logs_select_admin" ON public.sms_logs;
CREATE POLICY "sms_logs_select_admin"
  ON public.sms_logs
  FOR SELECT
  USING (public.is_admin());

REVOKE ALL ON public.sms_logs FROM anon, authenticated;
GRANT SELECT ON public.sms_logs TO authenticated;
GRANT ALL ON public.sms_logs TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.sms_logs_id_seq TO service_role;